#Requires -Version 5

$ErrorActionPreference = 'Stop'

$j       = [Environment]::ProcessorCount
$root    = $PSScriptRoot
$webRoot = Join-Path $root 'src\web'
$webDist = Join-Path $webRoot 'dist'
$out     = Join-Path $root 'build\cmd'
$outWeb  = Join-Path $out 'web'

Push-Location $webRoot
if (Test-Path "package-lock.json") {
    npm ci
    if ($LASTEXITCODE -ne 0) { Pop-Location; exit $LASTEXITCODE }
} else {
    npm install
    if ($LASTEXITCODE -ne 0) { Pop-Location; exit $LASTEXITCODE }
}
npm run build
if ($LASTEXITCODE -ne 0) { Pop-Location; exit $LASTEXITCODE }
Pop-Location

if (!(Test-Path (Join-Path $webDist 'index.html'))) {
    Write-Error "src\web\dist\index.html was not generated by npm run build."
    exit 1
}

cmake -S $root -B $out -DCMAKE_BUILD_TYPE=Release
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
cmake --build $out --target eversoul_console -j $j
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

if (!(Test-Path (Join-Path $outWeb 'index.html'))) {
    Write-Error "Web build output was not copied to build\cmd\web."
    exit 1
}

if (Test-Path "$root\copy_only\dll") {
    Copy-Item "$root\copy_only\dll\*" $out -Force
}
if (Test-Path "$root\copy_only\adb") {
    Copy-Item "$root\copy_only\adb\*" $out -Force
}

$cmake_temps = @('CMakeFiles','cmake_install.cmake','build.ninja','CMakeCache.txt','.ninja_deps','.ninja_log','web_embedded.cpp')
foreach ($t in $cmake_temps) {
    Remove-Item "$out\$t" -Recurse -Force -ErrorAction SilentlyContinue
}
