#!/usr/bin/env python3
"""Rebuild the /UserInfo payload so its formations reference the account's real heroes.

The captured fresh-account UserInfo has 4 starter heroes (heroNo 10/20/30/40) but all
formation slots are empty ("0"), so the tutorial battle fields nobody. This rewrites the
first two formations (no:0 and no:1) to place the 4 starter hero idx into the front slots,
keeping the rest of the payload byte-identical. Emits src/user_info_payload.inc.

Generic protobuf walk (no schema needed): UserInfo field 3 = repeated hero (idx=field1),
field 7 = repeated formation (heroidx = field3 repeated string).
"""
import re

# --- minimal protobuf reader/writer ---
def read_varint(b, i):
    v = 0; s = 0
    while True:
        x = b[i]; i += 1
        v |= (x & 0x7f) << s
        if not (x & 0x80): break
        s += 7
    return v, i

def write_varint(v):
    out = bytearray()
    while v >= 0x80:
        out.append((v & 0x7f) | 0x80); v >>= 7
    out.append(v)
    return bytes(out)

def tag(field, wt): return write_varint((field << 3) | wt)

def parse(b):
    """Return list of (field, wire, value) where value is bytes(len-delim)/int(varint)."""
    out = []; i = 0
    while i < len(b):
        key, i = read_varint(b, i)
        f, wt = key >> 3, key & 7
        if wt == 0:
            v, i = read_varint(b, i); out.append((f, wt, v))
        elif wt == 2:
            ln, i = read_varint(b, i); out.append((f, wt, b[i:i+ln])); i += ln
        elif wt == 1:
            out.append((f, wt, b[i:i+8])); i += 8
        elif wt == 5:
            out.append((f, wt, b[i:i+4])); i += 4
        else:
            raise ValueError(f"bad wire {wt}")
    return out

def emit(items):
    out = bytearray()
    for f, wt, v in items:
        out += tag(f, wt)
        if wt == 0:
            out += write_varint(v)
        elif wt == 2:
            out += write_varint(len(v)); out += v
        else:
            out += v
    return bytes(out)


def rewrite_formation(fbytes, hero_idxs):
    """Set the heroidx (field 3) list of one sFormation to hero_idxs, keep slot count."""
    items = parse(fbytes)
    # count existing heroidx slots
    n_slots = sum(1 for f, wt, v in items if f == 3 and wt == 2)
    if n_slots == 0:
        return fbytes  # not a battle formation we care about
    # build new field list: keep non-field3, replace field3 run with our idxs padded to n_slots
    new = []
    inserted = False
    for f, wt, v in items:
        if f == 3 and wt == 2:
            if not inserted:
                slots = list(hero_idxs) + ["0"] * (n_slots - len(hero_idxs))
                slots = slots[:n_slots]
                for s in slots:
                    new.append((3, 2, s.encode()))
                inserted = True
            # skip original field-3 entries
        else:
            new.append((f, wt, v))
    return emit(new)


def main():
    src = open("src/payloads.cpp").read()
    m = re.search(r'user_info_payload\(\).*?hex_to_bytes\(\s*(.*?)\);', src, re.S)
    hexstr = "".join(re.findall(r'"([0-9a-fA-F]+)"', m.group(1)))
    data = bytes.fromhex(hexstr)

    items = parse(data)
    # collect hero idx (field 3 = hero; each hero msg field1 = idx)
    hero_idxs = []
    for f, wt, v in items:
        if f == 3 and wt == 2:
            for hf, hwt, hv in parse(v):
                if hf == 1 and hwt == 2:
                    hero_idxs.append(hv.decode()); break
    print("starter heroes:", hero_idxs)

    # rewrite formations (field 7). Put the 4 starters into the first 2 formations (no:0, no:1).
    new_items = []
    formation_seen = 0
    for f, wt, v in items:
        if f == 7 and wt == 2:
            formation_seen += 1
            if formation_seen <= 2:  # default + battle formation #1
                v = rewrite_formation(v, hero_idxs)
        new_items.append((f, wt, v))
    out = emit(new_items)

    h = out.hex()
    lines = ['"' + h[i:i+96] + '"' for i in range(0, len(h), 96)]
    body = "// user_info_payload.inc - GENERATED by tools/build_userinfo.py.\n"
    body += "// Fresh-account UserInfo with the 4 starter heroes placed into formations 0 and 1\n"
    body += "// so the tutorial battle actually fields them.\n"
    body += "\n".join(lines) + "\n"
    open("src/user_info_payload.inc", "w").write(body)
    print(f"wrote src/user_info_payload.inc ({len(out)} bytes)")


if __name__ == "__main__":
    main()
