#!/usr/bin/env python3
"""Harvest real game-server response payloads from a session HAR into a C++ include.

Reads the live-kr game-server (port 1739) entries, strips the 8-byte response
envelope ([4-byte seq][4-byte size]) to keep only the protobuf payload, and emits
src/harvested_session.inc: a list of {path, hex-payload} the offline server replays
through game_binary_response(). For endpoints hit multiple times, the LAST occurrence
(final tutorial state) is kept.

Usage: python3 tools/harvest_har.py <session.har>
"""
import base64
import json
import sys
from urllib.parse import urlparse

# Endpoints whose responses MUST NOT be harvested into the session replay table.
# Developed-account mode disables Tutorial-named routes entirely; keeping captured
# tutorial payloads here can accidentally re-enable the new-user flow.
DYNAMIC = {"/Login", "/ServerTime", "/UserNicknameChange", "/FormationSave",
           "/HeroEquipMulti", "/TutorialActive", "/TutorialList",
           "/TutorialStoryClear", "/GachaHeroTutorial", "/GachaHeroTutorialFix",
           "/ArbeitTutorial"}


def resp_bytes(entry):
    content = entry["response"].get("content", {})
    text = content.get("text", "")
    if content.get("encoding") == "base64":
        return base64.b64decode(text)
    return text.encode("latin1", "ignore")


def main():
    if len(sys.argv) < 2:
        print("usage: harvest_har.py <session.har>", file=sys.stderr)
        return 1
    har = json.load(open(sys.argv[1]))
    entries = har["log"]["entries"]

    # path -> payload (last occurrence wins)
    harvested = {}
    for e in entries:
        u = urlparse(e["request"]["url"])
        if "live-kr.esoul" not in u.netloc and "live-sea.esoul" not in u.netloc:
            continue
        path = u.path
        if path in DYNAMIC:
            continue
        raw = resp_bytes(e)
        if len(raw) < 8:
            continue
        payload = raw[8:]  # strip [seq:4][size:4] envelope
        harvested[path] = payload

    out = []
    out.append("// harvested_session.inc - GENERATED by tools/harvest_har.py. Do not edit by hand.")
    out.append("// Real game-server response payloads (envelope stripped) from a login->tutorial")
    out.append("// session capture (table 4725, self-consistent). path -> protobuf payload bytes.")
    out.append("// Format: each entry is {path, hex}. Replayed via game_binary_response().")
    out.append("{")
    for path in sorted(harvested):
        payload = harvested[path]
        out.append(f'    // {path}  ({len(payload)} bytes)')
        out.append(f'    {{"{path}", "{payload.hex()}"}},')
    out.append("}")

    open("src/harvested_session.inc", "w").write("\n".join(out) + "\n")
    print(f"wrote src/harvested_session.inc: {len(harvested)} endpoints")
    for path in sorted(harvested):
        print(f"  {path:32s} {len(harvested[path])} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
