#!/usr/bin/env python3
"""cmake/gen_web_blob.py — src/web/* -> ESOFLND1 blob -> C++ source.

CMake add_custom_command 에서 호출됨.
사용법: python cmake/gen_web_blob.py <src/web_dir> <out.cpp>
"""
import os
import struct
import sys

MAGIC = b"ESOFLND1"
ALLOWED_EXTENSIONS = {
    ".html", ".js", ".css",
    ".png", ".ico", ".svg", ".webp", ".jpg", ".jpeg", ".gif",
    ".woff", ".woff2", ".ttf",
    ".json", ".txt",
}


def main():
    if len(sys.argv) < 3:
        print("usage: gen_web_blob.py <src_web_dir> <out.cpp>", file=sys.stderr)
        sys.exit(1)

    src_dir = sys.argv[1]
    out_cpp = sys.argv[2]

    entries = []
    for root, _dirs, files in os.walk(src_dir):
        for fname in sorted(files):
            full = os.path.join(root, fname)
            _, ext = os.path.splitext(fname)
            if ext.lower() not in ALLOWED_EXTENSIONS:
                continue
            with open(full, "rb") as f:
                data = f.read()
            rel_path = os.path.relpath(full, src_dir).replace(os.sep, "/")
            rel = "web/" + rel_path
            entries.append((rel.encode("utf-8"), data))
    entries.sort(key=lambda e: e[0])

    blob = bytearray()
    blob += MAGIC
    blob += struct.pack("<I", len(entries))
    for rel_b, data in entries:
        blob += struct.pack("<I", len(rel_b))
        blob += rel_b
        blob += struct.pack("<I", len(data))
        blob += data

    hex_lines = []
    for i in range(0, len(blob), 16):
        chunk = blob[i:i + 16]
        hex_lines.append("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")

    os.makedirs(os.path.dirname(os.path.abspath(out_cpp)), exist_ok=True)
    with open(out_cpp, "w", encoding="utf-8", newline="\n") as f:
        f.write("// AUTO-GENERATED by cmake/gen_web_blob.py -- DO NOT EDIT\n")
        f.write("#include <cstddef>\n")
        f.write("extern const unsigned char kWebBlobData[] = {\n")
        for line in hex_lines:
            f.write(line + "\n")
        f.write("};\n")
        f.write(f"extern const std::size_t kWebBlobSize = {len(blob)}UL;\n")

    names = [rel_b.decode() for rel_b, _ in entries]
    print(f"packed {len(entries)} web files -> {len(blob)} bytes: {out_cpp}")
    for n in names:
        print(f"  {n}")


if __name__ == "__main__":
    main()
